definitions:
  user__page:
    weight: -49
    menu_name: account
    parent: ''
    enabled: true
    expanded: false
  user__logout:
    weight: -48
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
