module:
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  foodtrucksmodule: 0
  geolocation: 0
  image: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  r4032login: 0
  rest: 0
  serialization: 0
  shortcut: 0
  simple_fb_connect: 0
  smtp: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  foodtruckstheme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
