definitions:
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__page:
    weight: -47
    menu_name: account
    parent: ''
    enabled: true
    expanded: false
  user__logout:
    weight: -50
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
